/* Generated by Yosys 0.33+6 (git sha1 41b34a193, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1694128612374/work=/usr/local/src/conda/yosys-0.33_7_g41b34a193 -fdebug-prefix-map=/home/marute/miniconda3/envs/digital=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

/* hdlname = "\\root_top" */
/* top =  1  */
/* src = "root_top.v:1.1-71.10" */
module root_top(clk, init, rst, A, raiz, done);
  /* src = "root_top.v:6.17-6.18" */
  input [7:0] A;
  wire [7:0] A;
  /* hdlname = "A_vAuxreg A_shift" */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:10.22-10.29" */
  wire [7:0] \A_vAuxreg.A_shift ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.A_shift_TRELLIS_FF_Q_2_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.A_shift_TRELLIS_FF_Q_3_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.A_shift_TRELLIS_FF_Q_4_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.A_shift_TRELLIS_FF_Q_5_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.A_shift_TRELLIS_FF_Q_6_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.A_shift_TRELLIS_FF_Q_7_DI ;
  wire \A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ;
  wire \A_vAuxreg.A_shift_TRELLIS_FF_Q_LSR ;
  /* hdlname = "A_vAuxreg LD" */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:3.11-3.13" */
  wire \A_vAuxreg.LD ;
  /* hdlname = "A_vAuxreg LDRes" */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:5.11-5.16" */
  wire \A_vAuxreg.LDRes ;
  wire \A_vAuxreg.LDRes_LUT4_C_Z ;
  wire \A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ;
  wire \A_vAuxreg.LD_TRELLIS_FF_Q_LSR ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ;
  /* hdlname = "A_vAuxreg SH0" */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:4.11-4.14" */
  wire \A_vAuxreg.SH0 ;
  /* hdlname = "A_vAuxreg clk" */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:2.11-2.14" */
  wire \A_vAuxreg.clk ;
  /* hdlname = "A_vAuxreg in_A" */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:6.17-6.21" */
  wire [7:0] \A_vAuxreg.in_A ;
  /* hdlname = "A_vAuxreg residuo" */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:7.17-7.24" */
  wire [7:0] \A_vAuxreg.residuo ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:12.16-12.30|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:63.22-63.23" */
  /* unused_bits = "1 3 5 7" */
  wire [7:0] \A_vAuxreg.residuo_CCU2C_S0_3_COUT ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:12.16-12.30|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:38.23-38.25" */
  /* unused_bits = "0 2 4 6 7" */
  wire [7:0] \A_vAuxreg.residuo_CCU2C_S0_COUT ;
  /* hdlname = "A_vAuxreg v_Aux" */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:9.22-9.27" */
  wire [7:0] \A_vAuxreg.v_Aux ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.v_Aux_TRELLIS_FF_Q_1_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.v_Aux_TRELLIS_FF_Q_2_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.v_Aux_TRELLIS_FF_Q_3_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.v_Aux_TRELLIS_FF_Q_4_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.v_Aux_TRELLIS_FF_Q_5_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.v_Aux_TRELLIS_FF_Q_6_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.v_Aux_TRELLIS_FF_Q_7_DI ;
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8" */
  wire \A_vAuxreg.v_Aux_TRELLIS_FF_Q_DI ;
  /* src = "root_top.v:22.6-22.9" */
  wire DEC;
  /* src = "root_top.v:3.11-3.14" */
  input clk;
  wire clk;
  /* hdlname = "cont0 DECI" */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:5.11-5.15" */
  wire \cont0.DECI ;
  wire \cont0.DECI_TRELLIS_FF_Q_DI ;
  wire \cont0.DECI_TRELLIS_FF_Q_LSR ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ;
  /* hdlname = "cont0 LD0" */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:4.11-4.14" */
  wire \cont0.LD0 ;
  /* hdlname = "cont0 clk" */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:3.11-3.14" */
  wire \cont0.clk ;
  /* hdlname = "cont0 out" */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:12.11-12.14" */
  wire [7:0] \cont0.out ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:18.20-18.27|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:63.22-63.23" */
  /* unused_bits = "3 5 7" */
  wire [7:0] \cont0.out_CCU2C_A0_3_COUT ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:18.20-18.27|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:38.23-38.25" */
  /* unused_bits = "2 4 6 7" */
  wire [7:0] \cont0.out_CCU2C_A0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:18.20-18.27|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:34.26-34.27" */
  wire [7:0] \cont0.out_TRELLIS_FF_Q_DI ;
  /* hdlname = "cont0 zero" */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:8.16-8.20" */
  wire \cont0.zero ;
  /* force_downto = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [3:0] \cont0.zero_LUT4_D_Z ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \cont0.zero_LUT4_D_Z_PFUMX_Z_ALUT ;
  wire \cont0.zero_TRELLIS_FF_Q_CE ;
  /* src = "root_top.v:51.14-55.6|contador_dec.v:19.21-19.29" */
  wire \cont0.zero_TRELLIS_FF_Q_DI ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] \cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_C0 ;
  /* hdlname = "control DEC" */
  /* src = "root_top.v:63.14-67.6|root_control.v:27.16-27.19" */
  wire \control.DEC ;
  /* hdlname = "control LD" */
  /* src = "root_top.v:63.14-67.6|root_control.v:23.16-23.18" */
  wire \control.LD ;
  /* hdlname = "control LDRes" */
  /* src = "root_top.v:63.14-67.6|root_control.v:24.16-24.21" */
  wire \control.LDRes ;
  /* hdlname = "control SH0" */
  /* src = "root_top.v:63.14-67.6|root_control.v:25.16-25.19" */
  wire \control.SH0 ;
  /* hdlname = "control SH1" */
  /* src = "root_top.v:63.14-67.6|root_control.v:26.16-26.19" */
  wire \control.SH1 ;
  wire \control.SH1_TRELLIS_FF_Q_LSR ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ;
  /* hdlname = "control clk" */
  /* src = "root_top.v:63.14-67.6|root_control.v:16.11-16.14" */
  wire \control.clk ;
  /* hdlname = "control count" */
  /* src = "root_top.v:63.14-67.6|root_control.v:36.15-36.20" */
  wire [4:0] \control.count ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:89.29-89.38|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:63.22-63.23" */
  /* unused_bits = "3 5" */
  wire [5:0] \control.count_CCU2C_B0_2_COUT ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:90.38-90.46|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:32.22-32.23" */
  wire [4:0] \control.count_CCU2C_B0_2_S0 ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:89.29-89.38|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:65.22-65.25" */
  /* unused_bits = "1 3 4 5" */
  wire [5:0] \control.count_CCU2C_B0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:89.29-89.38|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:65.27-65.29" */
  /* unused_bits = "1 3 4 5" */
  wire [5:0] \control.count_CCU2C_B0_S1 ;
  wire \control.count_TRELLIS_FF_Q_1_LSR ;
  wire \control.count_TRELLIS_FF_Q_2_LSR ;
  wire \control.count_TRELLIS_FF_Q_3_LSR ;
  wire \control.count_TRELLIS_FF_Q_4_LSR ;
  wire \control.count_TRELLIS_FF_Q_CE ;
  /* force_downto = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] \control.count_TRELLIS_FF_Q_DI ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:90.38-90.46|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:34.26-34.27" */
  /* unused_bits = "0 1 2 3 4" */
  wire [4:0] \control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0 ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:90.38-90.46|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:63.22-63.23" */
  /* unused_bits = "1 3 5" */
  wire [5:0] \control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0_CCU2C_S0_COUT ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control.count_TRELLIS_FF_Q_DI_LUT4_A_Z ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] \control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z ;
  wire \control.count_TRELLIS_FF_Q_LSR ;
  /* hdlname = "control current_state" */
  /* src = "root_top.v:63.14-67.6|root_control.v:35.15-35.28" */
  wire [2:0] \control.current_state ;
  /* force_downto = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:46.13-95.20|root_control.v:0.0-0.0|/home/marute/miniconda3/envs/digital/bin/../share/yosys/techmap.v:575.21-575.22" */
  wire [2:0] \control.current_state_TRELLIS_FF_Q_DI ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_1_BLUT ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ;
  /* hdlname = "control done" */
  /* src = "root_top.v:63.14-67.6|root_control.v:28.16-28.20" */
  wire \control.done ;
  /* hdlname = "control init" */
  /* src = "root_top.v:63.14-67.6|root_control.v:17.11-17.15" */
  wire \control.init ;
  /* hdlname = "control residuo_MSB" */
  /* src = "root_top.v:63.14-67.6|root_control.v:18.11-18.22" */
  wire \control.residuo_MSB ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control.residuo_MSB_LUT4_A_Z ;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control.residuo_MSB_LUT4_B_Z ;
  /* hdlname = "control rst" */
  /* src = "root_top.v:63.14-67.6|root_control.v:20.11-20.14" */
  wire \control.rst ;
  /* hdlname = "control zero" */
  /* src = "root_top.v:63.14-67.6|root_control.v:19.11-19.15" */
  wire \control.zero ;
  /* src = "root_top.v:9.12-9.16" */
  output done;
  wire done;
  wire done_TRELLIS_FF_Q_DI;
  wire done_TRELLIS_FF_Q_LSR;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire done_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire done_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT;
  /* src = "root_top.v:4.11-4.15" */
  input init;
  wire init;
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire init_LUT4_B_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] init_LUT4_D_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] init_LUT4_D_Z_LUT4_C_B;
  /* src = "root_top.v:18.6-18.10" */
  wire load;
  /* src = "root_top.v:19.6-19.17" */
  wire loadResiduo;
  /* hdlname = "rParcialreg DECI" */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:5.11-5.15" */
  wire \rParcialreg.DECI ;
  /* hdlname = "rParcialreg LD" */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:3.11-3.13" */
  wire \rParcialreg.LD ;
  /* hdlname = "rParcialreg SH1" */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:4.11-4.14" */
  wire \rParcialreg.SH1 ;
  /* hdlname = "rParcialreg clk" */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:2.11-2.14" */
  wire \rParcialreg.clk ;
  /* hdlname = "rParcialreg out_rParcial" */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:8.22-8.34" */
  wire [7:0] \rParcialreg.out_rParcial ;
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4" */
  wire \rParcialreg.out_rParcial_TRELLIS_FF_Q_1_DI ;
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4" */
  wire \rParcialreg.out_rParcial_TRELLIS_FF_Q_2_DI ;
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4" */
  wire \rParcialreg.out_rParcial_TRELLIS_FF_Q_3_DI ;
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4" */
  wire \rParcialreg.out_rParcial_TRELLIS_FF_Q_4_DI ;
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4" */
  wire \rParcialreg.out_rParcial_TRELLIS_FF_Q_5_DI ;
  wire \rParcialreg.out_rParcial_TRELLIS_FF_Q_CE ;
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4" */
  wire \rParcialreg.out_rParcial_TRELLIS_FF_Q_DI ;
  /* hdlname = "rParcialreg raiz" */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:6.17-6.21" */
  wire [7:0] \rParcialreg.raiz ;
  /* src = "root_top.v:8.18-8.22" */
  output [7:0] raiz;
  wire [7:0] raiz;
  /* hdlname = "raizReg LD" */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:4.11-4.13" */
  wire \raizReg.LD ;
  /* hdlname = "raizReg LDRes" */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:5.11-5.16" */
  wire \raizReg.LDRes ;
  /* hdlname = "raizReg SH1" */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:3.11-3.14" */
  wire \raizReg.SH1 ;
  /* hdlname = "raizReg clk" */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:2.11-2.14" */
  wire \raizReg.clk ;
  /* hdlname = "raizReg raiz" */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:7.22-7.26" */
  wire [7:0] \raizReg.raiz ;
  wire \raizReg.raiz_TRELLIS_FF_Q_LSR ;
  /* src = "root_top.v:5.11-5.14" */
  input rst;
  wire rst;
  /* src = "root_top.v:21.6-21.11" */
  wire shift;
  /* src = "root_top.v:20.6-20.19" */
  wire shift2_vAux_A;
  /* hdlname = "sum_res_comp20 in_B" */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:2.17-2.21" */
  wire [7:0] \sum_res_comp20.in_B ;
  /* hdlname = "sum_res_comp20 in_vAux" */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:3.17-3.24" */
  wire [7:0] \sum_res_comp20.in_vAux ;
  /* hdlname = "sum_res_comp20 residuo" */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:5.22-5.29" */
  wire [7:0] \sum_res_comp20.residuo ;
  /* hdlname = "sum_res_comp20 residuo_MSB" */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:6.16-6.27" */
  wire \sum_res_comp20.residuo_MSB ;
  /* src = "root_top.v:14.12-14.22" */
  wire [7:0] w_rParcial;
  /* src = "root_top.v:12.12-12.18" */
  wire [7:0] w_raiz;
  /* src = "root_top.v:16.12-16.21" */
  wire [7:0] w_residuo;
  /* src = "root_top.v:15.6-15.19" */
  wire w_residuo_MSB;
  /* src = "root_top.v:13.12-13.18" */
  wire [7:0] w_vAux;
  /* src = "root_top.v:24.6-24.12" */
  wire w_zero;
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q  (
    .CE(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A[1]),
    .LSR(\A_vAuxreg.A_shift_TRELLIS_FF_Q_LSR ),
    .Q(\A_vAuxreg.A_shift [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_1  (
    .CE(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A[0]),
    .LSR(\A_vAuxreg.A_shift_TRELLIS_FF_Q_LSR ),
    .Q(\A_vAuxreg.A_shift [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_2  (
    .CE(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\A_vAuxreg.A_shift_TRELLIS_FF_Q_2_DI ),
    .LSR(1'h0),
    .Q(\A_vAuxreg.A_shift [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[7]),
    .C(\A_vAuxreg.A_shift [5]),
    .D(\A_vAuxreg.LD ),
    .Z(\A_vAuxreg.A_shift_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_3  (
    .CE(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\A_vAuxreg.A_shift_TRELLIS_FF_Q_3_DI ),
    .LSR(1'h0),
    .Q(\A_vAuxreg.A_shift [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_3_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[6]),
    .C(\A_vAuxreg.A_shift [4]),
    .D(\A_vAuxreg.LD ),
    .Z(\A_vAuxreg.A_shift_TRELLIS_FF_Q_3_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_4  (
    .CE(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\A_vAuxreg.A_shift_TRELLIS_FF_Q_4_DI ),
    .LSR(1'h0),
    .Q(\A_vAuxreg.A_shift [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_4_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[5]),
    .C(\A_vAuxreg.A_shift [3]),
    .D(\A_vAuxreg.LD ),
    .Z(\A_vAuxreg.A_shift_TRELLIS_FF_Q_4_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_5  (
    .CE(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\A_vAuxreg.A_shift_TRELLIS_FF_Q_5_DI ),
    .LSR(1'h0),
    .Q(\A_vAuxreg.A_shift [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_5_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[4]),
    .C(\A_vAuxreg.A_shift [2]),
    .D(\A_vAuxreg.LD ),
    .Z(\A_vAuxreg.A_shift_TRELLIS_FF_Q_5_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_6  (
    .CE(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\A_vAuxreg.A_shift_TRELLIS_FF_Q_6_DI ),
    .LSR(1'h0),
    .Q(\A_vAuxreg.A_shift [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_6_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[3]),
    .C(\A_vAuxreg.A_shift [1]),
    .D(\A_vAuxreg.LD ),
    .Z(\A_vAuxreg.A_shift_TRELLIS_FF_Q_6_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_7  (
    .CE(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\A_vAuxreg.A_shift_TRELLIS_FF_Q_7_DI ),
    .LSR(1'h0),
    .Q(\A_vAuxreg.A_shift [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_7_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[2]),
    .C(\A_vAuxreg.A_shift [0]),
    .D(\A_vAuxreg.LD ),
    .Z(\A_vAuxreg.A_shift_TRELLIS_FF_Q_7_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_CE_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\A_vAuxreg.LD ),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.A_shift_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \A_vAuxreg.A_shift_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\A_vAuxreg.LD ),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.A_shift_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \A_vAuxreg.LDRes_LUT4_C  (
    .A(1'h0),
    .B(1'h0),
    .C(\A_vAuxreg.LDRes ),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.LDRes_LUT4_C_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.LDRes_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(done_TRELLIS_FF_Q_DI),
    .LSR(\A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR ),
    .Q(\A_vAuxreg.LDRes )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z  (
    .ALUT(\A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ),
    .BLUT(\A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ),
    .C0(\control.current_state [1]),
    .Z(\A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control.residuo_MSB ),
    .B(\control.current_state [2]),
    .C(rst),
    .D(\control.current_state [0]),
    .Z(\A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hfcff)
  ) \A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control.current_state [2]),
    .C(rst),
    .D(\control.current_state [0]),
    .Z(\A_vAuxreg.LDRes_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.LD_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\cont0.DECI_TRELLIS_FF_Q_DI ),
    .LSR(\A_vAuxreg.LD_TRELLIS_FF_Q_LSR ),
    .Q(\A_vAuxreg.LD )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z  (
    .ALUT(\A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ),
    .BLUT(\A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ),
    .C0(\control.current_state [2]),
    .Z(\A_vAuxreg.LD_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h3033)
  ) \A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(rst),
    .C(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .D(\control.current_state [1]),
    .Z(\A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3332)
  ) \A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT_LUT4_Z  (
    .A(\control.current_state [0]),
    .B(rst),
    .C(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .D(\control.current_state [1]),
    .Z(\A_vAuxreg.LD_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.SH0_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(done_TRELLIS_FF_Q_DI),
    .LSR(\A_vAuxreg.LD_TRELLIS_FF_Q_LSR ),
    .Q(\A_vAuxreg.SH0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:12.16-12.30|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \A_vAuxreg.residuo_CCU2C_S0  (
    .A0(\A_vAuxreg.v_Aux [6]),
    .A1(\A_vAuxreg.v_Aux [7]),
    .B0(\rParcialreg.out_rParcial [6]),
    .B1(\rParcialreg.out_rParcial [7]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\A_vAuxreg.residuo_CCU2C_S0_3_COUT [6]),
    .COUT(\A_vAuxreg.residuo_CCU2C_S0_COUT [7]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\A_vAuxreg.residuo [6]),
    .S1(\control.residuo_MSB )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:12.16-12.30|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \A_vAuxreg.residuo_CCU2C_S0_1  (
    .A0(\A_vAuxreg.v_Aux [4]),
    .A1(\A_vAuxreg.v_Aux [5]),
    .B0(\rParcialreg.out_rParcial [4]),
    .B1(\rParcialreg.out_rParcial [5]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\A_vAuxreg.residuo_CCU2C_S0_3_COUT [4]),
    .COUT(\A_vAuxreg.residuo_CCU2C_S0_3_COUT [6]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\A_vAuxreg.residuo [4]),
    .S1(\A_vAuxreg.residuo [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:12.16-12.30|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \A_vAuxreg.residuo_CCU2C_S0_2  (
    .A0(\A_vAuxreg.v_Aux [2]),
    .A1(\A_vAuxreg.v_Aux [3]),
    .B0(\rParcialreg.out_rParcial [2]),
    .B1(\rParcialreg.out_rParcial [3]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\A_vAuxreg.residuo_CCU2C_S0_3_COUT [2]),
    .COUT(\A_vAuxreg.residuo_CCU2C_S0_3_COUT [4]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\A_vAuxreg.residuo [2]),
    .S1(\A_vAuxreg.residuo [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:57.15-61.6|sum_res_comp2.v:12.16-12.30|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \A_vAuxreg.residuo_CCU2C_S0_3  (
    .A0(\A_vAuxreg.v_Aux [0]),
    .A1(\A_vAuxreg.v_Aux [1]),
    .B0(\rParcialreg.out_rParcial [0]),
    .B1(\rParcialreg.out_rParcial [1]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(1'h1),
    .COUT(\A_vAuxreg.residuo_CCU2C_S0_3_COUT [2]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\A_vAuxreg.residuo [0]),
    .S1(\A_vAuxreg.residuo [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q  (
    .CE(\A_vAuxreg.LDRes_LUT4_C_Z ),
    .CLK(clk),
    .DI(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\A_vAuxreg.v_Aux [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_1  (
    .CE(\A_vAuxreg.LDRes_LUT4_C_Z ),
    .CLK(clk),
    .DI(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_1_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\A_vAuxreg.v_Aux [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(1'h0),
    .B(\A_vAuxreg.v_Aux [4]),
    .C(\A_vAuxreg.residuo [6]),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_2  (
    .CE(\A_vAuxreg.LDRes_LUT4_C_Z ),
    .CLK(clk),
    .DI(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_2_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\A_vAuxreg.v_Aux [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(1'h0),
    .B(\A_vAuxreg.v_Aux [3]),
    .C(\A_vAuxreg.residuo [5]),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_3  (
    .CE(\A_vAuxreg.LDRes_LUT4_C_Z ),
    .CLK(clk),
    .DI(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_3_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\A_vAuxreg.v_Aux [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_3_DI_LUT4_Z  (
    .A(1'h0),
    .B(\A_vAuxreg.v_Aux [2]),
    .C(\A_vAuxreg.residuo [4]),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_3_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_4  (
    .CE(\A_vAuxreg.LDRes_LUT4_C_Z ),
    .CLK(clk),
    .DI(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_4_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\A_vAuxreg.v_Aux [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_4_DI_LUT4_Z  (
    .A(1'h0),
    .B(\A_vAuxreg.v_Aux [1]),
    .C(\A_vAuxreg.residuo [3]),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_4_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_5  (
    .CE(\A_vAuxreg.LDRes_LUT4_C_Z ),
    .CLK(clk),
    .DI(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_5_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\A_vAuxreg.v_Aux [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_5_DI_LUT4_Z  (
    .A(1'h0),
    .B(\A_vAuxreg.v_Aux [0]),
    .C(\A_vAuxreg.residuo [2]),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_5_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_6  (
    .CE(\A_vAuxreg.LDRes_LUT4_C_Z ),
    .CLK(clk),
    .DI(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_6_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\A_vAuxreg.v_Aux [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_6_DI_LUT4_Z  (
    .A(1'h0),
    .B(\A_vAuxreg.A_shift [7]),
    .C(\A_vAuxreg.residuo [1]),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_6_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:32.13-36.6|lsr2_vAux_A.v:16.5-26.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_7  (
    .CE(\A_vAuxreg.LDRes_LUT4_C_Z ),
    .CLK(clk),
    .DI(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_7_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\A_vAuxreg.v_Aux [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_7_DI_LUT4_Z  (
    .A(1'h0),
    .B(\A_vAuxreg.A_shift [6]),
    .C(\A_vAuxreg.residuo [0]),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_7_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \A_vAuxreg.v_Aux_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\A_vAuxreg.v_Aux [5]),
    .C(\control.residuo_MSB ),
    .D(\A_vAuxreg.SH0 ),
    .Z(\A_vAuxreg.v_Aux_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.DECI_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\cont0.DECI_TRELLIS_FF_Q_DI ),
    .LSR(\cont0.DECI_TRELLIS_FF_Q_LSR ),
    .Q(\cont0.DECI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hff10)
  ) \cont0.DECI_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .B(\cont0.zero_LUT4_D_Z [1]),
    .C(\cont0.zero_LUT4_D_Z [2]),
    .D(rst),
    .Z(\cont0.DECI_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z  (
    .ALUT(\cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ),
    .BLUT(\cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ),
    .C0(\control.current_state [2]),
    .Z(\cont0.DECI_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hfffc)
  ) \cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(\control.current_state [0]),
    .C(rst),
    .D(\control.current_state [1]),
    .Z(\cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hf1ff)
  ) \cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT_LUT4_Z  (
    .A(\control.residuo_MSB ),
    .B(\control.current_state [0]),
    .C(rst),
    .D(\control.current_state [1]),
    .Z(\cont0.DECI_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:18.20-18.27|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \cont0.out_CCU2C_A0  (
    .A0(\cont0.out [6]),
    .A1(\cont0.out [7]),
    .B0(1'h0),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\cont0.out_CCU2C_A0_3_COUT [6]),
    .COUT(\cont0.out_CCU2C_A0_COUT [7]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\cont0.out_TRELLIS_FF_Q_DI [6]),
    .S1(\cont0.out_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:18.20-18.27|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \cont0.out_CCU2C_A0_1  (
    .A0(\cont0.out [4]),
    .A1(\cont0.out [5]),
    .B0(1'h0),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\cont0.out_CCU2C_A0_3_COUT [4]),
    .COUT(\cont0.out_CCU2C_A0_3_COUT [6]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\cont0.out_TRELLIS_FF_Q_DI [4]),
    .S1(\cont0.out_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:18.20-18.27|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \cont0.out_CCU2C_A0_2  (
    .A0(\cont0.out [2]),
    .A1(\cont0.out [3]),
    .B0(1'h0),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\cont0.out_CCU2C_A0_3_COUT [2]),
    .COUT(\cont0.out_CCU2C_A0_3_COUT [4]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\cont0.out_TRELLIS_FF_Q_DI [2]),
    .S1(\cont0.out_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:18.20-18.27|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \cont0.out_CCU2C_A0_3  (
    .A0(\cont0.out [0]),
    .A1(\cont0.out [1]),
    .B0(1'h1),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(1'h1),
    .COUT(\cont0.out_CCU2C_A0_3_COUT [2]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\cont0.out_TRELLIS_FF_Q_DI [0]),
    .S1(\cont0.out_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.out_TRELLIS_FF_Q  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\cont0.out_TRELLIS_FF_Q_DI [7]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\cont0.out [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.out_TRELLIS_FF_Q_1  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\cont0.out_TRELLIS_FF_Q_DI [6]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\cont0.out [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.out_TRELLIS_FF_Q_2  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\cont0.out_TRELLIS_FF_Q_DI [5]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\cont0.out [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.out_TRELLIS_FF_Q_3  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\cont0.out_TRELLIS_FF_Q_DI [4]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\cont0.out [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.out_TRELLIS_FF_Q_4  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\cont0.out_TRELLIS_FF_Q_DI [3]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\cont0.out [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.out_TRELLIS_FF_Q_5  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\cont0.out_TRELLIS_FF_Q_DI [2]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\cont0.out [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:82.168-82.227" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("SET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.out_TRELLIS_FF_Q_6  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\cont0.out_TRELLIS_FF_Q_DI [1]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\cont0.out [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:82.168-82.227" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("SET"),
    .SRMODE("LSR_OVER_CE")
  ) \cont0.out_TRELLIS_FF_Q_7  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\cont0.out_TRELLIS_FF_Q_DI [0]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\cont0.out [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \cont0.zero_LUT4_D  (
    .A(1'h0),
    .B(\control.current_state [1]),
    .C(\control.current_state [2]),
    .D(\cont0.zero ),
    .Z(\cont0.zero_LUT4_D_Z [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfcff)
  ) \cont0.zero_LUT4_D_Z_LUT4_C  (
    .A(1'h0),
    .B(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .C(\cont0.zero_LUT4_D_Z [1]),
    .D(\cont0.zero_LUT4_D_Z [2]),
    .Z(\control.current_state_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \cont0.zero_LUT4_D_Z_PFUMX_Z  (
    .ALUT(\cont0.zero_LUT4_D_Z_PFUMX_Z_ALUT ),
    .BLUT(init_LUT4_B_Z),
    .C0(\control.current_state [1]),
    .Z(\cont0.zero_LUT4_D_Z [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hf0fc)
  ) \cont0.zero_LUT4_D_Z_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(\control.residuo_MSB ),
    .C(\control.current_state [0]),
    .D(\control.current_state [2]),
    .Z(\cont0.zero_LUT4_D_Z_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:51.14-55.6|contador_dec.v:14.5-21.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \cont0.zero_TRELLIS_FF_Q  (
    .CE(\cont0.zero_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\cont0.zero_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\cont0.zero )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \cont0.zero_TRELLIS_FF_Q_CE_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\A_vAuxreg.LD ),
    .D(\cont0.DECI ),
    .Z(\cont0.zero_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z  (
    .ALUT(\cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ),
    .BLUT(\cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ),
    .C0(\cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_C0 [4]),
    .Z(\cont0.zero_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\cont0.out [4]),
    .B(\cont0.out [5]),
    .C(\cont0.out [6]),
    .D(\cont0.out [7]),
    .Z(\cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_C0_LUT4_Z  (
    .A(\cont0.out [0]),
    .B(\cont0.out [1]),
    .C(\cont0.out [2]),
    .D(\cont0.out [3]),
    .Z(\cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_C0 [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.SH1_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\cont0.DECI_TRELLIS_FF_Q_DI ),
    .LSR(\control.SH1_TRELLIS_FF_Q_LSR ),
    .Q(\control.SH1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z  (
    .ALUT(\control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ),
    .BLUT(\control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ),
    .C0(rst),
    .Z(\control.SH1_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h00bf)
  ) \control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT_LUT4_Z  (
    .A(\control.current_state [1]),
    .B(\control.current_state [0]),
    .C(\control.current_state [2]),
    .D(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .Z(\control.SH1_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:89.29-89.38|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control.count_CCU2C_B0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control.count [4]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control.count_CCU2C_B0_2_COUT [4]),
    .COUT(\control.count_CCU2C_B0_COUT [4]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control.count_TRELLIS_FF_Q_DI [1]),
    .S1(\control.count_CCU2C_B0_S1 [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:89.29-89.38|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control.count_CCU2C_B0_1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control.count [2]),
    .B1(\control.count [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control.count_CCU2C_B0_2_COUT [2]),
    .COUT(\control.count_CCU2C_B0_2_COUT [4]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control.count_CCU2C_B0_2_S0 [2]),
    .S1(\control.count_CCU2C_B0_2_S0 [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:89.29-89.38|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control.count_CCU2C_B0_2  (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\control.count [0]),
    .B1(\control.count [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\control.count_CCU2C_B0_2_COUT [2]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control.count_CCU2C_B0_2_S0 [0]),
    .S1(\control.count_CCU2C_B0_2_S0 [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:39.5-97.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.count_TRELLIS_FF_Q  (
    .CE(\control.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control.count_TRELLIS_FF_Q_DI [1]),
    .LSR(\control.count_TRELLIS_FF_Q_LSR ),
    .Q(\control.count [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:39.5-97.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.count_TRELLIS_FF_Q_1  (
    .CE(\control.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control.count_CCU2C_B0_2_S0 [3]),
    .LSR(\control.count_TRELLIS_FF_Q_1_LSR ),
    .Q(\control.count [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control.count_TRELLIS_FF_Q_1_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(init_LUT4_D_Z[1]),
    .Z(\control.count_TRELLIS_FF_Q_1_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:39.5-97.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.count_TRELLIS_FF_Q_2  (
    .CE(\control.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control.count_CCU2C_B0_2_S0 [2]),
    .LSR(\control.count_TRELLIS_FF_Q_2_LSR ),
    .Q(\control.count [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control.count_TRELLIS_FF_Q_2_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(init_LUT4_D_Z[1]),
    .Z(\control.count_TRELLIS_FF_Q_2_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:39.5-97.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.count_TRELLIS_FF_Q_3  (
    .CE(\control.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control.count_CCU2C_B0_2_S0 [1]),
    .LSR(\control.count_TRELLIS_FF_Q_3_LSR ),
    .Q(\control.count [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control.count_TRELLIS_FF_Q_3_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(init_LUT4_D_Z[1]),
    .Z(\control.count_TRELLIS_FF_Q_3_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:39.5-97.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.count_TRELLIS_FF_Q_4  (
    .CE(\control.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control.count_CCU2C_B0_2_S0 [0]),
    .LSR(\control.count_TRELLIS_FF_Q_4_LSR ),
    .Q(\control.count [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control.count_TRELLIS_FF_Q_4_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(init_LUT4_D_Z[1]),
    .Z(\control.count_TRELLIS_FF_Q_4_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:90.38-90.46|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control.count_TRELLIS_FF_Q_DI_CCU2C_COUT  (
    .A0(1'h1),
    .A1(1'h1),
    .B0(\control.count_CCU2C_B0_2_S0 [2]),
    .B1(\control.count_CCU2C_B0_2_S0 [3]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0_CCU2C_S0_COUT [2]),
    .COUT(\control.count_TRELLIS_FF_Q_DI [0]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0 [2]),
    .S1(\control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0 [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:90.38-90.46|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0_CCU2C_S0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control.count_CCU2C_B0_2_S0 [0]),
    .B1(\control.count_CCU2C_B0_2_S0 [1]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(1'h1),
    .COUT(\control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0_CCU2C_S0_COUT [2]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0 [0]),
    .S1(\control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0 [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hb000)
  ) \control.count_TRELLIS_FF_Q_DI_LUT4_A  (
    .A(\control.count_TRELLIS_FF_Q_DI [0]),
    .B(\control.count_TRELLIS_FF_Q_DI [1]),
    .C(\control.current_state [0]),
    .D(\control.current_state [1]),
    .Z(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT  (
    .ALUT(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z ),
    .BLUT(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_BLUT ),
    .C0(\control.current_state [2]),
    .Z(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control.count_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(init_LUT4_D_Z[1]),
    .Z(\control.count_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:39.5-97.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.current_state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control.current_state_TRELLIS_FF_Q_DI [2]),
    .LSR(rst),
    .Q(\control.current_state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:39.5-97.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.current_state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control.current_state_TRELLIS_FF_Q_DI [1]),
    .LSR(rst),
    .Q(\control.current_state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:63.14-67.6|root_control.v:39.5-97.8|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control.current_state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\control.current_state_TRELLIS_FF_Q_DI [0]),
    .LSR(rst),
    .Q(\control.current_state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z  (
    .ALUT(\control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ),
    .BLUT(\control.residuo_MSB_LUT4_B_Z ),
    .C0(\control.current_state [2]),
    .Z(\control.current_state_TRELLIS_FF_Q_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_1  (
    .ALUT(\control.residuo_MSB_LUT4_A_Z ),
    .BLUT(\control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_1_BLUT ),
    .C0(\control.current_state [1]),
    .Z(\control.current_state_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_1_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .D(\control.current_state [0]),
    .Z(\control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_1_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff0f)
  ) \control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control.current_state [1]),
    .D(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .Z(\control.current_state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hf0f1)
  ) \control.residuo_MSB_LUT4_A  (
    .A(\control.residuo_MSB ),
    .B(\control.current_state [2]),
    .C(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .D(\control.current_state [0]),
    .Z(\control.residuo_MSB_LUT4_A_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hffe0)
  ) \control.residuo_MSB_LUT4_B  (
    .A(\control.current_state [0]),
    .B(\control.residuo_MSB ),
    .C(\control.current_state [1]),
    .D(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .Z(\control.residuo_MSB_LUT4_B_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) done_TRELLIS_FF_Q (
    .CLK(clk),
    .DI(done_TRELLIS_FF_Q_DI),
    .LSR(done_TRELLIS_FF_Q_LSR),
    .Q(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h00ef)
  ) done_TRELLIS_FF_Q_DI_LUT4_Z (
    .A(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .B(\cont0.zero_LUT4_D_Z [1]),
    .C(\cont0.zero_LUT4_D_Z [2]),
    .D(rst),
    .Z(done_TRELLIS_FF_Q_DI)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX done_TRELLIS_FF_Q_LSR_PFUMX_Z (
    .ALUT(done_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT),
    .BLUT(done_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT),
    .C0(rst),
    .Z(done_TRELLIS_FF_Q_LSR)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) done_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h00bf)
  ) done_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT_LUT4_Z (
    .A(\control.current_state [1]),
    .B(\control.current_state [0]),
    .C(\control.current_state [2]),
    .D(\control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3]),
    .Z(done_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hf0f3)
  ) init_LUT4_B (
    .A(1'h0),
    .B(init),
    .C(\control.current_state [0]),
    .D(\control.current_state [2]),
    .Z(init_LUT4_B_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0100)
  ) init_LUT4_D (
    .A(\control.current_state [1]),
    .B(\control.current_state [2]),
    .C(\control.current_state [0]),
    .D(init),
    .Z(init_LUT4_D_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h00fc)
  ) init_LUT4_D_Z_LUT4_C (
    .A(1'h0),
    .B(init_LUT4_D_Z_LUT4_C_B[0]),
    .C(init_LUT4_D_Z[1]),
    .D(rst),
    .Z(\control.count_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc000)
  ) init_LUT4_D_Z_LUT4_C_B_LUT4_Z (
    .A(1'h0),
    .B(\control.current_state [1]),
    .C(\control.current_state [2]),
    .D(\control.current_state [0]),
    .Z(init_LUT4_D_Z_LUT4_C_B[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q  (
    .CE(\rParcialreg.out_rParcial_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rParcialreg.out_rParcial_TRELLIS_FF_Q_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\rParcialreg.out_rParcial [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_1  (
    .CE(\rParcialreg.out_rParcial_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rParcialreg.out_rParcial_TRELLIS_FF_Q_1_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\rParcialreg.out_rParcial [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rParcialreg.out_rParcial [4]),
    .C(\raizReg.raiz [6]),
    .D(\control.SH1 ),
    .Z(\rParcialreg.out_rParcial_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_2  (
    .CE(\rParcialreg.out_rParcial_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rParcialreg.out_rParcial_TRELLIS_FF_Q_2_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\rParcialreg.out_rParcial [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rParcialreg.out_rParcial [3]),
    .C(\raizReg.raiz [5]),
    .D(\control.SH1 ),
    .Z(\rParcialreg.out_rParcial_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_3  (
    .CE(\rParcialreg.out_rParcial_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rParcialreg.out_rParcial_TRELLIS_FF_Q_3_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\rParcialreg.out_rParcial [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_3_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rParcialreg.out_rParcial [2]),
    .C(\raizReg.raiz [4]),
    .D(\control.SH1 ),
    .Z(\rParcialreg.out_rParcial_TRELLIS_FF_Q_3_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_4  (
    .CE(\rParcialreg.out_rParcial_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rParcialreg.out_rParcial_TRELLIS_FF_Q_4_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\rParcialreg.out_rParcial [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_4_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rParcialreg.out_rParcial [1]),
    .C(\raizReg.raiz [3]),
    .D(\control.SH1 ),
    .Z(\rParcialreg.out_rParcial_TRELLIS_FF_Q_4_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_5  (
    .CE(\rParcialreg.out_rParcial_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rParcialreg.out_rParcial_TRELLIS_FF_Q_5_DI ),
    .LSR(\A_vAuxreg.LD ),
    .Q(\rParcialreg.out_rParcial [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_5_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rParcialreg.out_rParcial [0]),
    .C(\raizReg.raiz [2]),
    .D(\control.SH1 ),
    .Z(\rParcialreg.out_rParcial_TRELLIS_FF_Q_5_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_6  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\raizReg.raiz [1]),
    .LSR(\raizReg.raiz_TRELLIS_FF_Q_LSR ),
    .Q(\rParcialreg.out_rParcial [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:38.15-42.6|lsr2_rParcial.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:82.168-82.227" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("SET"),
    .SRMODE("LSR_OVER_CE")
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_7  (
    .CE(\cont0.DECI ),
    .CLK(clk),
    .DI(\raizReg.raiz [0]),
    .LSR(\raizReg.raiz_TRELLIS_FF_Q_LSR ),
    .Q(\rParcialreg.out_rParcial [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_CE_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control.SH1 ),
    .D(\cont0.DECI ),
    .Z(\rParcialreg.out_rParcial_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \rParcialreg.out_rParcial_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rParcialreg.out_rParcial [5]),
    .C(\raizReg.raiz [7]),
    .D(\control.SH1 ),
    .Z(\rParcialreg.out_rParcial_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \raizReg.raiz_TRELLIS_FF_Q  (
    .CE(\A_vAuxreg.LDRes ),
    .CLK(clk),
    .DI(1'h1),
    .LSR(\raizReg.raiz_TRELLIS_FF_Q_LSR ),
    .Q(\raizReg.raiz [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \raizReg.raiz_TRELLIS_FF_Q_1  (
    .CE(\control.SH1 ),
    .CLK(clk),
    .DI(\raizReg.raiz [6]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\raizReg.raiz [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \raizReg.raiz_TRELLIS_FF_Q_2  (
    .CE(\control.SH1 ),
    .CLK(clk),
    .DI(\raizReg.raiz [5]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\raizReg.raiz [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \raizReg.raiz_TRELLIS_FF_Q_3  (
    .CE(\control.SH1 ),
    .CLK(clk),
    .DI(\raizReg.raiz [4]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\raizReg.raiz [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \raizReg.raiz_TRELLIS_FF_Q_4  (
    .CE(\control.SH1 ),
    .CLK(clk),
    .DI(\raizReg.raiz [3]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\raizReg.raiz [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \raizReg.raiz_TRELLIS_FF_Q_5  (
    .CE(\control.SH1 ),
    .CLK(clk),
    .DI(\raizReg.raiz [2]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\raizReg.raiz [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \raizReg.raiz_TRELLIS_FF_Q_6  (
    .CE(\control.SH1 ),
    .CLK(clk),
    .DI(\raizReg.raiz [1]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\raizReg.raiz [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "root_top.v:44.10-48.6|lsr_raiz.v:11.1-19.4|/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \raizReg.raiz_TRELLIS_FF_Q_7  (
    .CE(\control.SH1 ),
    .CLK(clk),
    .DI(\raizReg.raiz [0]),
    .LSR(\A_vAuxreg.LD ),
    .Q(\raizReg.raiz [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/marute/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \raizReg.raiz_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\A_vAuxreg.LD ),
    .D(\control.SH1 ),
    .Z(\raizReg.raiz_TRELLIS_FF_Q_LSR )
  );
  assign \cont0.zero_TRELLIS_FF_Q_DI_PFUMX_Z_C0 [3:0] = \cont0.out [7:4];
  assign { \cont0.zero_LUT4_D_Z [3], \cont0.zero_LUT4_D_Z [0] } = { rst, \control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [3] };
  assign init_LUT4_D_Z[0] = rst;
  assign init_LUT4_D_Z_LUT4_C_B[2:1] = { rst, init_LUT4_D_Z[1] };
  assign \control.count_TRELLIS_FF_Q_DI [4:2] = \control.current_state ;
  assign { \control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [4], \control.count_TRELLIS_FF_Q_DI_LUT4_A_Z_PFUMX_ALUT_Z [2:0] } = { rst, \control.current_state [2], \control.current_state [0], \control.current_state [1] };
  assign \control.count_CCU2C_B0_2_S0 [4] = \control.count_TRELLIS_FF_Q_DI [1];
  assign { \control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0_CCU2C_S0_COUT [4], \control.count_TRELLIS_FF_Q_DI_CCU2C_COUT_S0_CCU2C_S0_COUT [0] } = { \control.count_TRELLIS_FF_Q_DI [0], 1'h1 };
  assign \cont0.out_CCU2C_A0_3_COUT [1:0] = { \cont0.out [0], 1'h1 };
  assign \cont0.out_CCU2C_A0_COUT [6:0] = { \cont0.out_CCU2C_A0_3_COUT [7:2], \cont0.out [0] };
  assign \control.count_CCU2C_B0_2_COUT [1:0] = { \control.count [0], 1'h0 };
  assign { \control.count_CCU2C_B0_COUT [2], \control.count_CCU2C_B0_COUT [0] } = { \control.count_CCU2C_B0_2_COUT [4], \control.count_CCU2C_B0_2_COUT [2] };
  assign { \control.count_CCU2C_B0_S1 [2], \control.count_CCU2C_B0_S1 [0] } = { \control.count_CCU2C_B0_2_S0 [3], \control.count_CCU2C_B0_2_S0 [1] };
  assign \A_vAuxreg.residuo_CCU2C_S0_3_COUT [0] = 1'h1;
  assign \A_vAuxreg.residuo_CCU2C_S0_COUT [6:0] = \A_vAuxreg.residuo_CCU2C_S0_3_COUT [7:1];
  assign \A_vAuxreg.clk  = clk;
  assign \A_vAuxreg.in_A  = A;
  assign \A_vAuxreg.residuo [7] = \control.residuo_MSB ;
  assign DEC = \cont0.DECI ;
  assign \cont0.LD0  = \A_vAuxreg.LD ;
  assign \cont0.clk  = clk;
  assign \control.DEC  = \cont0.DECI ;
  assign \control.LD  = \A_vAuxreg.LD ;
  assign \control.LDRes  = \A_vAuxreg.LDRes ;
  assign \control.SH0  = \A_vAuxreg.SH0 ;
  assign \control.clk  = clk;
  assign \control.done  = done;
  assign \control.init  = init;
  assign \control.rst  = rst;
  assign \control.zero  = \cont0.zero ;
  assign load = \A_vAuxreg.LD ;
  assign loadResiduo = \A_vAuxreg.LDRes ;
  assign \rParcialreg.DECI  = \cont0.DECI ;
  assign \rParcialreg.LD  = \A_vAuxreg.LD ;
  assign \rParcialreg.SH1  = \control.SH1 ;
  assign \rParcialreg.clk  = clk;
  assign \rParcialreg.raiz  = \raizReg.raiz ;
  assign raiz = \raizReg.raiz ;
  assign \raizReg.LD  = \A_vAuxreg.LD ;
  assign \raizReg.LDRes  = \A_vAuxreg.LDRes ;
  assign \raizReg.SH1  = \control.SH1 ;
  assign \raizReg.clk  = clk;
  assign shift = \control.SH1 ;
  assign shift2_vAux_A = \A_vAuxreg.SH0 ;
  assign \sum_res_comp20.in_B  = \rParcialreg.out_rParcial ;
  assign \sum_res_comp20.in_vAux  = \A_vAuxreg.v_Aux ;
  assign \sum_res_comp20.residuo  = { \control.residuo_MSB , \A_vAuxreg.residuo [6:0] };
  assign \sum_res_comp20.residuo_MSB  = \control.residuo_MSB ;
  assign w_rParcial = \rParcialreg.out_rParcial ;
  assign w_raiz = \raizReg.raiz ;
  assign w_residuo = { \control.residuo_MSB , \A_vAuxreg.residuo [6:0] };
  assign w_residuo_MSB = \control.residuo_MSB ;
  assign w_vAux = \A_vAuxreg.v_Aux ;
  assign w_zero = \cont0.zero ;
endmodule
